# Generated by Django 6.1 on 2026-08-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('calle_1', models.CharField(max_length=150)),
                ('calle_2', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_siniestro', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'siniestros',
                'managed': False,
            },
        ),
    ]
