# Generated by Django 5.2.17 on 2026-09-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={},
        ),
    ]
