# Generated by Django 5.2.17 on 2026-09-04 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siniestro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestro',
            name='origen',
            field=models.CharField(choices=[('AUTOMATICO', 'Automático (IA - Scraping)'), ('MANUAL', 'Carga Manual (Web)')], default='AUTOMATICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='calle_1',
            field=models.CharField(help_text='Ubicación o intersección', max_length=255),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='calle_2',
            field=models.CharField(blank=True, help_text='Fuente o detalles adicionales', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='tipo_siniestro',
            field=models.CharField(default='Colisión', max_length=100),
        ),
        migrations.AlterModelTable(
            name='siniestro',
            table=None,
        ),
    ]
